# Generated by Django 4.0.1 on 2023-08-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_code', models.PositiveIntegerField()),
                ('e_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], max_length=1)),
                ('e_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
